version: '3.3'

services:
  flask-app:
    container_name: flask-app
    image: ${IMAGE}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${EXPOSED_PORT}:5002
    command: bash -c "gunicorn --capture-output --enable-stdio-inheritance -w 1 --threads 4 -b 0.0.0.0:5002 app:app --timeout 1000"
    networks:
      - shared_network
    restart: always

networks:
  shared_network:
    # Remove the 'external' declaration
    # external:
    #   name: shared_network

